package com.trading.platform.eztrade.security.dto;

/**
 * Response that encapsulates the JWT token information generated after authentication.
 * <p>
 * Includes the token itself and the authentication scheme type used in the
 * <strong>Authorization</strong> header.
 */
public class JwtResponse {

    /**
     * Signed JWT token that the client will use to authenticate subsequent requests.
     */
    private final String token;

    /**
     * Token type used in the <strong>Authorization</strong> header.
     * The <strong>Bearer</strong> scheme is used by default.
     */
    private final String type = "Bearer";

    /**
     * Creates a new JWT response with the provided token.
     *
     * @param token JWT token generated by the authentication system
     */
    public JwtResponse(String token) {
        this.token = token;
    }

    /**
     * Returns the JWT token.
     *
     * @return signed JWT token
     */
    public String getToken() {
        return token;
    }

    /**
     * Returns the token type in use.
     *
     * @return token type, usually <strong>Bearer</strong>
     */
    public String getType() {
        return type;
    }
}


