package com.trading.platform.eztrade.portfolio.domain.events;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Event published when a SELL leaves the position quantity at zero.
 *
 * @param owner owning user
 * @param symbol closed symbol
 * @param realizedPnlDelta PnL generated by the closing sale
 * @param totalRealizedPnl accumulated realized PnL after closing
 * @param occurredAt event publication timestamp
 */
public record PositionClosedEvent(
        String owner,
        String symbol,
        BigDecimal realizedPnlDelta,
        BigDecimal totalRealizedPnl,
        LocalDateTime occurredAt
) {
}

